### ISSUE TITLE
missing rocks in the mines

### ISSUE THREAD

**Issue by Unsafebreacher** [someone0002/stellar-feedback#12]
**Describe the bug**
[A clear and concise description of what the bug is. **Remove this line!**]

**To Reproduce**
Steps to reproduce the behaviour:
2. Do '....'
3. And also do '....'

**Expected Behaviour**
[A clear and concise description of what you expected to happen. **Remove this line!**]

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by someone0002** [comment]
This isn't filled out..?
