### ISSUE TITLE
Nos is unusable

### ISSUE THREAD

**Issue by Blakewolf00** [someone0002/stellar-feedback#15]
So in vehicles the purple nos symbol is now blur and now when we hit shift/ a on controller it doesn't activate the NOS.

**Comment by someone0002** [comment]
https://github.com/someone0002/afterlife-main/commit/3a9fe9f01e38322c2e4531af8a5baeaa6362cc08

**Comment by someone0002** [comment]
[@3a9fe9f](https://github.com/someone0002/afterlife-main/commit/3a9fe9f01e38322c2e4531af8a5baeaa6362cc08) Fixed

**Comment by someone0002** [comment]
@3a9fe9fhttps://github.com/someone0002/afterlife-main/commit/3a9fe9f01e38322c2e4531af8a5baeaa6362cc08
