### ISSUE TITLE
Storage at the Auto Exotics

### ISSUE THREAD

**Issue by labatts68** [someone0002/stellar-feedback#7]
**Describe the bug**
It would appear that after exiting the storage room i crash error GTA5_b2372.exe!sub_14060dd64, this has happened multiple times. The loss of parts and money is overwhelming.
**To Reproduce**
Steps to reproduce the behaviour:
1. Enter SStorage
2. leave storage
3. wait approx 5 - 10 min, 

**Expected Behaviour**
 a resolution MT the storage, then delete the storage, then place a new storage under my name

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by someone0002** [comment]
Investigated this and issue has been found. 

Will release patch today.
